import type { VedicContent } from '@/types';

export const vedicContent: VedicContent[] = [
  {
    id: 'gita-1',
    title: 'Bhagavad Gita: Chapter 1 - Arjuna Vishada Yoga',
    sanskrit: 'धर्मक्षेत्रे कुरुक्षेत्रे समवेता युयुत्सवः। मामकाः पाण्डवाश्चैव किमकुर्वत सञ्जय॥',
    transliteration: 'Dharmakshetre Kurukshetre samaveta yuyutsavah, mamakah Pandavashchaiva kimakurvata Sanjaya.',
    hindi: 'हे संजय! धर्मभूमि कुरुक्षेत्र में एकत्रित हुए युद्धाभिलाषी मेरे और पाण्डवों के पुत्रों ने क्या किया?',
    english: 'O Sanjaya, what did my sons and the sons of Pandu do when they gathered on the holy field of Kurukshetra, eager for battle?',
    explanation: 'The first chapter sets the stage for the great war. It introduces the key warriors and Arjuna\'s moral dilemma about fighting his own kin.',
    philosophy: 'This chapter represents the inner conflict every human faces when choosing between duty and attachments.',
    source: 'Bhagavad Gita',
    chapter: 'Chapter 1',
  },
  {
    id: 'gita-2',
    title: 'Bhagavad Gita: Chapter 2 - Sankhya Yoga',
    sanskrit: 'क्लैब्यं मा स्म गमः पार्थ नैतत्त्वय्युपपद्यते। क्षुद्रं हृदयदौर्बल्यं त्यक्त्वोत्तिष्ठ परन्तप॥',
    transliteration: 'Klaibyam ma sma gamah Partha naitattvayyupapadyate, kshudram hridayadaurbalyam tyaktvottishtha parantapa.',
    hindi: 'हे पार्थ! इस नपुंसकता को प्राप्त मत होओ। यह तुम्हें शोभा नहीं देता। हृदय की इस तुच्छ दुर्बलता को त्यागकर उठो, हे परंतप!',
    english: 'Do not yield to unmanliness, O Parth. It does not become you. Cast off this petty weakness of heart and arise, O scorcher of enemies!',
    explanation: 'Lord Krishna urges Arjuna to fight, explaining the eternal nature of the soul which is never born nor dies.',
    philosophy: 'This chapter introduces the concept of the immortal soul (Atman) and the importance of performing one\'s duty without attachment.',
    source: 'Bhagavad Gita',
    chapter: 'Chapter 2',
  },
  {
    id: 'gita-3',
    title: 'Bhagavad Gita: Chapter 3 - Karma Yoga',
    sanskrit: 'मा फलेषु कदाचन। मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि॥',
    transliteration: 'Ma phaleshu kadachana, ma karmaphalaheturbhurma te sangostvakarmani.',
    hindi: 'कर्म पर अपना अधिकार है, फलों पर कभी नहीं। इसलिए तू कर्मफल का हेतु मत बन और न ही कर्म न करने में आसक्ति रख।',
    english: 'You have a right to perform your prescribed duties, but you are not entitled to the fruits of your actions. Never consider yourself to be the cause of the results of your activities, and never be attached to not doing your duty.',
    explanation: 'Lord Krishna teaches the path of selfless action (Karma Yoga) - performing one\'s duty without attachment to results.',
    philosophy: 'This is one of the most practical teachings - focus on the action, not the outcome. This leads to freedom from anxiety.',
    source: 'Bhagavad Gita',
    chapter: 'Chapter 3',
  },
  {
    id: 'upanishad-1',
    title: 'Isha Upanishad',
    sanskrit: 'ईशा वास्यमिदं सर्वं यत्किञ्च जगत्यां जगत्। तेन त्यक्तेन भुञ्जीथा मा गृधः कस्यस्विद्धनम्॥',
    transliteration: 'Isha vasyamidam sarvam yatkincha jagatyam jagat, tena tyaktena bhunjitha ma gridhah kasyasviddhanam.',
    hindi: 'इस संसार में जो कुछ भी है, सब ईश्वर से व्याप्त है। उसके त्याग से भोगो। किसी के धन का लोभ मत करो।',
    english: 'All this - whatever exists in this changing universe - is pervaded by the Lord. Renounce it and enjoy it. Do not covet anybody\'s wealth.',
    explanation: 'The Isha Upanishad teaches that the entire universe is permeated by the divine consciousness.',
    philosophy: 'True fulfillment comes not from accumulation but from recognizing the divine in all and living with detachment.',
    source: 'Isha Upanishad',
    chapter: 'Complete',
  },
  {
    id: 'upanishad-2',
    title: 'Kena Upanishad',
    sanskrit: 'केनेषितं पतति प्रेषितं मनः केन प्राणः प्रथमः प्रैति युक्तः। केनेषितां वाचमिमां वदन्ति चक्षुः श्रोत्रं क उ देवो युनक्ति॥',
    transliteration: 'Keneshitam patati preshitam manah kena pranah prathamah praiti yuktah, keneshitam vachamimam vadanti chakshuh shrotram ka u devo yunakti.',
    hindi: 'किसकी प्रेरणा से मन गतिमान होता है? किसके द्वारा जीवन-शक्ति कार्य करती है? किसकी इच्छा से वाणी बोलती है? कौन देवता आँख और कान को चलाता है?',
    english: 'By whom impelled does the mind fall upon its objects? By whom directed does the life-force begin its functions? By whose will does speech utter? Who is the god that directs the eyes and ears?',
    explanation: 'The Kena Upanishad explores the source of consciousness and the power behind all sensory and mental activities.',
    philosophy: 'The ultimate reality (Brahman) is beyond the senses and mind - it is that which makes perception possible.',
    source: 'Kena Upanishad',
    chapter: 'Complete',
  },
  {
    id: 'veda-1',
    title: 'Rigveda - Creation Hymn (Nasadiya Sukta)',
    sanskrit: 'नासदासीन्नो सदासीत्तदानीं नासीद्रजो नो व्योमा परो यत्। किमावरीवः कुह कस्य शर्मन्नम्भः किमासीद्गहनं गभीरम्॥',
    transliteration: 'Nasadasinno sadasittadanim nasidrajo no vyoma paro yat, kimavarivah kuha kya sharmannambhah kimasidgahanam gabhiram.',
    hindi: 'उस समय न सत् था, न असत् था। न अंतरिक्ष था, न आकाश था। क्या ढका था? कहाँ? किसके सुरक्षा में? क्या गहन जल था?',
    english: 'There was neither non-existence nor existence then. There was neither the realm of space nor the sky beyond. What covered it? Where was it? In whose keeping? Was there water, deep and unfathomable?',
    explanation: 'This famous hymn from the Rigveda contemplates the mystery of creation and the origin of the universe.',
    philosophy: 'Even in ancient times, Vedic seers contemplated profound cosmological questions, showing the deep philosophical nature of Vedic thought.',
    source: 'Rigveda',
    chapter: 'Book 10, Hymn 129',
  },
  {
    id: 'sloka-1',
    title: 'Gayatri Mantra',
    sanskrit: 'ॐ भूर्भुवः स्वः तत्सवितुर्वरेण्यं भर्गो देवस्य धीमहि धियो यो नः प्रचोदयात्॥',
    transliteration: 'Om Bhur Bhuvah Svah, Tat Savitur Varenyam, Bhargo Devasya Dheemahi, Dhiyo Yo Nah Prachodayat.',
    hindi: 'ॐ, भूः, भुवः, स्वः। उस प्रकाशमान, पूजनीय देव की उपासना करते हैं। वह हमारी बुद्धि को सही मार्ग पर प्रेरित करे।',
    english: 'Om, Earth, Sky, Heaven. We meditate on the divine light of the Sun. May it illuminate our minds.',
    explanation: 'The Gayatri Mantra is one of the most sacred mantras in Hinduism, addressed to the Sun as the source of all life and consciousness.',
    philosophy: 'This mantra is a prayer for spiritual illumination and the awakening of the intellect.',
    source: 'Rigveda',
    chapter: 'Mandala 3, Hymn 62',
  },
  {
    id: 'sloka-2',
    title: 'Shanti Mantra',
    sanskrit: 'ॐ सह नाववतु सह नौ भुनक्तु सह वीर्यं करवावहै तेजस्वि नावधीतमस्तु मा विद्विषावहै॥',
    transliteration: 'Om Saha Navavatu Saha Nau Bhunaktu Saha Viryam Karavavahai Tejasvi Navadhitamastu Ma Vidvishavahai.',
    hindi: 'ॐ, वह हम दोनों की रक्षा करे, हम दोनों का पोषण करे, हम दोनों मिलकर कार्य करें, हमारा अध्ययन तेजस्वी हो, हमारे बीच द्वेष न हो।',
    english: 'Om. May He protect us both. May He nourish us both. May we work together with energy. May our study be enlightening. May there be no animosity between us.',
    explanation: 'This is a peace invocation often chanted at the beginning and end of Vedic study sessions.',
    philosophy: 'The mantra emphasizes harmony, cooperation, and the collective pursuit of knowledge.',
    source: 'Krishna Yajurveda',
    chapter: 'Taittiriya Upanishad',
  },
];

export const vedicCategories = [
  { id: 'all', name: 'All', icon: 'book-open' },
  { id: 'Bhagavad Gita', name: 'Bhagavad Gita', icon: 'gita' },
  { id: 'Upanishads', name: 'Upanishads', icon: 'om' },
  { id: 'Rigveda', name: 'Rigveda', icon: 'veda' },
  { id: 'Mantras', name: 'Mantras & Slokas', icon: 'mantra' },
];
